namespace VacationHire.RentalService.Responses
{
    /// <summary>
    ///     This is an internal response to a rental request
    /// </summary>
    public class RentRequestResult
    {
        /// <summary>
        ///     Each request has a unique identifier: for this demo purpose, it gets generated by the system
        /// In a real live scenario, this would be a unique identifier generated by the rental tracking system
        /// </summary>
        public int RentRequestId { get; set; }

        /// <summary>
        ///     The id of the object being rented
        /// </summary>
        public int RentableAssetId { get; set; }
    }
}